name: DIGITALOCEAN_DEPLOY

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Discard all local git changes
        run: git checkout -- .
      - uses: actions/checkout@v2
        continue-on-error: true
      - name: Remove images from local
        run: docker images -aq | xargs --no-run-if-empty docker rmi -f $(docker images -aq)
        continue-on-error: true

      - name: Run build
        run: docker-compose up --build -d
